name       : blueman
version    : 2.0.4
release    : 3
source     :
    - https://github.com/blueman-project/blueman/releases/download/2.0.4/blueman-2.0.4.tar.xz : e92dd9c27f75a1485b548f7a8b159946a4af154b90fb82f5a0f614b66a01430f
license    : GPL-3.0
component  : desktop.mate
summary    : GTK+ Bluetooth manager
description: |
    GTK+ Bluetooth manager
builddeps  :
    - pkgconfig(gnome-icon-theme)
    - pkgconfig(python-2.7)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(polkit-agent-1)
    - pkgconfig(bluez)
    - cython
rundeps    :
    - python-gobject
setup      : |
    %configure --enable-settings-integration --disable-static
build      : |
    %make
install    : |
    %make_install
    # Stateless.
    mv $installdir/etc/dbus-1/* $installdir/usr/share/dbus-1/.
    rmdir $installdir/etc/dbus-1
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
