name       : blueman
version    : 2.0.6
release    : 5
source     :
    - https://github.com/blueman-project/blueman/archive/2.0.6.tar.gz : fc827768c607c1ee54db89332e3b8046b89c286d41df490b5985733c61bdea33
license    : GPL-3.0
component  : desktop.mate
summary    : GTK+ Bluetooth manager
description: |
    GTK+ Bluetooth manager
builddeps  :
    - pkgconfig(gnome-icon-theme)
    - pkgconfig(python-2.7)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(polkit-agent-1)
    - pkgconfig(bluez)
    - cython
rundeps    :
    - python-gobject
setup      : |
    %autogen --enable-settings-integration --disable-static
build      : |
    %make
install    : |
    %make_install
    # Stateless.
    mv $installdir/etc/dbus-1/* $installdir/usr/share/dbus-1/.
    rmdir $installdir/etc/dbus-1
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
    # Keyrules per: https://github.com/blueman-project/blueman/wiki/PolicyKit
    install -Dm00644 $pkgfiles/org.blueman.keyrules $installdir/usr/share/polkit-1/rules.d/org.blueman.keyrules
