name       : blueman
version    : 2.2.4
release    : 19
source     :
    - https://github.com/blueman-project/blueman/releases/download/2.2.4/blueman-2.2.4.tar.gz : 36db3dc11a90b344940e27db0bc43e0134b8c5f28e0c9827aa9208fc3ebdfe67
homepage   : https://github.com/blueman-project/blueman
license    : GPL-3.0-or-later
component  : desktop.mate
summary    : GTK+ Bluetooth manager
description: |
    Blueman is a GTK+ Bluetooth Manager. It is designed to provide a simple yet effective means for controlling the BlueZ API and simplifying Bluetooth tasks.
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(polkit-agent-1)
    - pkgconfig(pygobject-3.0)
    - cython
rundeps    :
    - python-gobject
setup      : |
    %configure  --disable-static \
        --enable-settings-integration \
        --enable-thunar-sendto=no \
        --sysconfdir=/usr/share
build      : |
    %make
install    : |
    %make_install

    # Keyrules per: https://github.com/blueman-project/blueman/wiki/PolicyKit
    install -Dm00644 $pkgfiles/org.blueman.keyrules $installdir/usr/share/polkit-1/rules.d/org.blueman.keyrules
