name       : blueman
version    : 2.1.2
release    : 15
source     :
    - https://github.com/blueman-project/blueman/releases/download/2.1.2/blueman-2.1.2.tar.xz : 517db22cdf5b80af7865efb3fdf0d056fb549ba63b7f39d9d7346bfafc83894c
license    : GPL-3.0-or-later
component  : desktop.mate
summary    : GTK+ Bluetooth manager
description: |
    Blueman is a GTK+ Bluetooth Manager
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(polkit-agent-1)
    - pkgconfig(pygobject-3.0)
    - cython
rundeps    :
    - python-gobject
setup      : |
    sed -e 's|/usr/sbin/bluetoothd|%libdir%/bluetooth/bluetoothd|g' -i apps/blueman-report.in

    %configure  --disable-static \
        --enable-settings-integration \
        --enable-thunar-sendto=no
build      : |
    %make
install    : |
    %make_install
    # Stateless.
    mv $installdir/etc/dbus-1/* $installdir/usr/share/dbus-1/.
    rmdir $installdir/etc/dbus-1
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
    # Keyrules per: https://github.com/blueman-project/blueman/wiki/PolicyKit
    install -Dm00644 $pkgfiles/org.blueman.keyrules $installdir/usr/share/polkit-1/rules.d/org.blueman.keyrules
