name       : blueman
version    : 2.3.1
release    : 21
source     :
    - https://github.com/blueman-project/blueman/releases/download/2.3.1/blueman-2.3.1.tar.gz : 1cada83e7122f705b82ba3df6d29debacf775f8c5bb122c32b2bd46fb60a393d
homepage   : https://github.com/blueman-project/blueman
license    : GPL-3.0-or-later
component  : desktop.mate
summary    : GTK+ Bluetooth manager
description: |
    Blueman is a GTK+ Bluetooth Manager. It is designed to provide a simple yet effective means for controlling the BlueZ API and simplifying Bluetooth tasks.
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(polkit-agent-1)
    - pkgconfig(pygobject-3.0)
    - cython
rundeps    :
    - python-gobject
setup      : |
    # Solus uses the sudo group instead of wheel
    sed -i "s|wheel|sudo|" data/configs/blueman.rules

    %configure  --disable-static \
        --enable-settings-integration \
        --enable-thunar-sendto=no \
        --sysconfdir=/usr/share
build      : |
    %make
install    : |
    %make_install

    # Rename polkit rules file for consistency
    mv $installdir/usr/share/polkit-1/rules.d/blueman.rules $installdir/usr/share/polkit-1/rules.d/org.blueman.rules
