name       : blueman
version    : 2.1.3
release    : 17
source     :
    - https://github.com/blueman-project/blueman/releases/download/2.1.3/blueman-2.1.3.tar.xz : 3bd02e0cc9e2c1424df1fc2015da710a280ef4c657515727e47eafabf8c2cfde
license    : GPL-3.0-or-later
component  : desktop.mate
summary    : GTK+ Bluetooth manager
description: |
    Blueman is a GTK+ Bluetooth Manager
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(polkit-agent-1)
    - pkgconfig(pygobject-3.0)
    - cython
rundeps    :
    - python-gobject
setup      : |
    sed -e 's|/usr/sbin/bluetoothd|%libdir%/bluetooth/bluetoothd|g' -i apps/blueman-report.in

    %configure  --disable-static \
        --enable-settings-integration \
        --enable-thunar-sendto=no
build      : |
    %make
install    : |
    %make_install
    # Stateless.
    mv $installdir/etc/dbus-1/* $installdir/usr/share/dbus-1/.
    rmdir $installdir/etc/dbus-1
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
    # Keyrules per: https://github.com/blueman-project/blueman/wiki/PolicyKit
    install -Dm00644 $pkgfiles/org.blueman.keyrules $installdir/usr/share/polkit-1/rules.d/org.blueman.keyrules
