name       : blueman
version    : 2.3.5
release    : 22
source     :
    - https://github.com/blueman-project/blueman/releases/download/2.3.5/blueman-2.3.5.tar.gz : 2feb9288c3f547175ea3b619b9023c1f556aa79a8c6c4602965bd475fbc023f3
homepage   : https://github.com/blueman-project/blueman
license    : GPL-3.0-or-later
component  : desktop.mate
summary    : GTK+ Bluetooth manager
description: |
    Blueman is a GTK+ Bluetooth Manager. It is designed to provide a simple yet effective means for controlling the BlueZ API and simplifying Bluetooth tasks.
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(polkit-agent-1)
    - pkgconfig(pygobject-3.0)
    - cython
rundeps    :
    - python-gobject
setup      : |
    # Solus uses the sudo group instead of wheel
    sed -i "s|wheel|sudo|" data/configs/blueman.rules

    %configure  --disable-static \
        --enable-settings-integration \
        --enable-thunar-sendto=no \
        --sysconfdir=/usr/share
build      : |
    %make
install    : |
    %make_install

    # Rename polkit rules file for consistency
    mv $installdir/usr/share/polkit-1/rules.d/blueman.rules $installdir/usr/share/polkit-1/rules.d/org.blueman.rules
